go.property("player_id", "")

function init(self)
  msg.post(".", "acquire_input_focus")
end

function update(self, dt)
  -- 서버에서 받은 위치를 이곳에서 반영
  if self.target_pos then
      local pos = go.get_position()
      pos.x = self.target_pos.x
      pos.y = self.target_pos.y
      go.set_position(pos)
  end
end

function on_message(self, message_id, message, sender)
  if message_id == hash("update_position") then
      self.target_pos = vmath.vector3(message.x, message.y, 0)
  end
end